name: Deploy CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
      
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Cache
        uses: actions/cache@v3
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}
      
      - name: Build
        run: |
          yarn install
          yarn build
          
      - name: SSH Key Generate
        run: |
           mkdir -p ~/.ssh/
           echo "${{ secrets.SSH_PASSWORD }}" > ~/.ssh/id_ed25519
           chmod 600 ~/.ssh/id_ed25519
        
      - name: Deploy SSH
        run: rsync -ahvz -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SSH_PORT }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./build/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER }}:${{ secrets.SSH_REMOTE_ROOT }}
